### PR TITLE
Add matomo

### PR DESCRIPTION
**Pull request by sierramatice**

### CODE REVIEW

**Review by mcjustin — CHANGES_REQUESTED** [review]
@sierramatice  It would be better to put that js block in a single file "assets/js/matomo.js". You'll want to exclude the opening `<script type="text/javascript">` and closing `</script>` lines, and you can ditch the "Matomo" comments.

Then where you added it to each file in the head, instead refer to that new file like this: 
`<script src="assets/js/matomo.js"></script>`
Note that the other existing js files are included at the bottom of the html files, but I think we do want the matomo included at the head.

**Comment by sierramatice** [comment]
@mcjustin changed to match your comment above

**Review by mcjustin — APPROVED** [review]
Thanks for making that change!

**Comment by sierramatice** [comment]
@mcjustin no problem!

**Pull request merged**
